services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  postgres_data: